/*
 * Zapier AI Actions API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ExecuteResponse
 */
public class ExecuteResponseTest {
    private final ExecuteResponse model = new ExecuteResponse();

    /**
     * Model tests for ExecuteResponse
     */
    @Test
    public void testExecuteResponse() {
        // TODO: test ExecuteResponse
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'actionUsed'
     */
    @Test
    public void actionUsedTest() {
        // TODO: test actionUsed
    }

    /**
     * Test the property 'inputParams'
     */
    @Test
    public void inputParamsTest() {
        // TODO: test inputParams
    }

    /**
     * Test the property 'reviewUrl'
     */
    @Test
    public void reviewUrlTest() {
        // TODO: test reviewUrl
    }

    /**
     * Test the property 'result'
     */
    @Test
    public void resultTest() {
        // TODO: test result
    }

    /**
     * Test the property 'additionalResults'
     */
    @Test
    public void additionalResultsTest() {
        // TODO: test additionalResults
    }

    /**
     * Test the property 'resultFieldLabels'
     */
    @Test
    public void resultFieldLabelsTest() {
        // TODO: test resultFieldLabels
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'error'
     */
    @Test
    public void errorTest() {
        // TODO: test error
    }

    /**
     * Test the property 'assistantHint'
     */
    @Test
    public void assistantHintTest() {
        // TODO: test assistantHint
    }

}
