/*
 * Zapier AI Actions API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.ExecuteResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for LogApi
 */
@Disabled
public class LogApiTest {

    private static LogApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new LogApi(apiClient);
    }

    /**
     * Get Execution Log Endpoint
     *
     * Get the execution log for a given execution log id.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getExecutionLogTest() throws ApiException {
        String executionLogId = null;
        ExecuteResponse response = api.getExecutionLog(executionLogId)
                .execute();
        // TODO: test validations
    }

}
